events {
    worker_connections 1024;
}

http {
    # Definimos el grupo de servidores backend (App A y App B)
    # Nginx por defecto usa un algoritmo de Round Robin (uno y uno)
    upstream api_servers {
        server app_a:8000;
        server app_b:8000;
    }

    server {
        listen 8000;

        location / {
            proxy_pass http://api_servers;
            
            # Pasamos los headers originales para no perder la trazabilidad
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
