"""Initial migration

Revision ID: 001_initial
Revises: 
Create Date: 2026-07-31 00:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.Enum('PLATFORM_ACCESS', 'TECH_SUPPORT', 'ACADEMIC', 'ADMINISTRATIVE', name='solicitudetype'), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='solicitudepriority'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='solicitudestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_external_id'), 'solicitudes', ['external_id'], unique=True)
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_external_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    sa.Enum('PLATFORM_ACCESS', 'TECH_SUPPORT', 'ACADEMIC', 'ADMINISTRATIVE', name='solicitudetype').drop(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', name='solicitudepriority').drop(op.get_bind())
    sa.Enum('RECEIVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='solicitudestatus').drop(op.get_bind())
    # ### end Alembic commands ###
